config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:update]
  get 'users/profile'
  get 'users/mypage'
end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 1, name: '18歳未満' },
    { id: 2, name: '18歳' },
    { id: 3, name: '19歳' },
    { id: 4, name: '20歳' },
    { id: 5, name: '21歳' },
    { id: 6, name: '22歳' },
    { id: 7, name: '23歳' },
    { id: 8, name: '24歳' },
    { id: 9, name: '25歳' },
    { id: 10, name: '26歳' },
    { id: 11, name: '27歳' },
    { id: 12, name: '28歳' },
    { id: 13, name: '29歳' },
    { id: 14, name: '30歳' },
    { id: 15, name: '31歳' },
    { id: 16, name: '32歳' },
    { id: 17, name: '33歳' },
    { id: 18, name: '34歳' },
    { id: 19, name: '35歳' },
    { id: 20, name: '36歳' },
    { id: 21, name: '37歳' },
    { id: 22, name: '38歳' },
    { id: 23, name: '39歳' },
    { id: 24, name: '40歳' },
    { id: 25, name: '41歳' },
    { id: 26, name: '42歳' },
    { id: 27, name: '43歳' },
    { id: 28, name: '44歳' },
    { id: 29, name: '45歳' },
    { id: 30, name: '46歳' },
    { id: 31, name: '47歳' },
    { id: 32, name: '48歳' },
    { id: 33, name: '49歳' },
    { id: 34, name: '50歳' },
    { id: 35, name: '51歳' },
    { id: 36, name: '52歳' },
    { id: 37, name: '53歳' },
    { id: 38, name: '54歳' },
    { id: 39, name: '55歳' },
    { id: 40, name: '56歳' },
    { id: 41, name: '57歳' },
    { id: 42, name: '58歳' },
    { id: 43, name: '59歳' },
    { id: 44, name: '60歳以上' },
  ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1,  type: '男性' },
    { id: 2,  type: '女性' },
    { id: 3,  type: 'その他' },
  ]
end

app/models/job.rb
class Job < ActiveHash::Base
  self.data = [
    { id: 1, name: 'エンジニア' },
    { id: 2, name: 'デザイナー' },
    { id: 3, name: 'ライター' },
    { id: 4, name: 'アーティスト' },
    { id: 5, name: '教師' },
    { id: 6, name: '医師' },
    { id: 7, name: '弁護士' },
    { id: 8, name: '会計士' },
    { id: 9, name: 'マーケター' },
    { id: 10, name: 'セールス' },
    { id: 11, name: 'コンサルタント' },
    { id: 12, name: '経営者' },
    { id: 13, name: '公務員' },
    { id: 14, name: '警察官' },
    { id: 15, name: '消防士' },
    { id: 16, name: '自衛官' },
    { id: 17, name: '漁師' },
    { id: 18, name: '農家' },
    { id: 19, name: '飲食店スタッフ' },
    { id: 20, name: '接客業' },
    { id: 21, name: '学生' },
    { id: 22, name: '会社員' },
    { id: 23, name: 'その他' },
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' }, { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' }, { id: 6, name: '山形県' },
    { id: 7, name: '福島県' }, { id: 8, name: '茨城県' }, { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' }, { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' }, { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' }, { id: 17, name: '石川県' }, { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' }, { id: 20, name: '長野県' }, { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' }, { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' }, { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' }, { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' }, { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' }, { id: 35, name: '山口県' }, { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' }, { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' }, { id: 44, name: '大分県' }, { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }, { id: 48, name: '海外' },
  ]
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  before_create :default_avatar

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture, optional: true
  belongs_to_active_hash :age, optional: true
  belongs_to_active_hash :gender, optional: true
  belongs_to_active_hash :job, optional: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: [:twitter2]

  def thumbnail
    avatar.variant(resize: '100x100').processed
  end

  def default_avatar
    if !avatar.attached?
      avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'noimage.png')),
                    filename: 'default-avatar.png', content_type: 'image/png')
    end
  end

  def self.find_for_oauth(auth)
    user = User.find_by(uid: auth.uid, provider: auth.provider)

    user ||= User.create!(
      uid: auth.uid,
      provider: auth.provider,
      username: auth[:info][:nickname],
      email: User.dummy_email(auth),
      password: Devise.friendly_token[0, 20],
      confirmed_at: Time.now.utc
    )
    user
  end

  def self.dummy_email(auth)
    "#{Time.now.strftime('%Y%m%d%H%M%S').to_i}-#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :name, :introduction, :prefecture_id,
      :age_id, :gender_id, :job_id,
    ])
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :name, :introduction, :prefecture_id,
      :age_id, :gender_id, :job_id,
    ])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter2
    callback_from :twitter2
  end

  private

  def callback_from(provider)
    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    logger.info("[TWITTER LOGIN] @user.inspect=#{@user.inspect}")
    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, expect: [:index]

  def index
  end

  def mypage
    @user = current_user
  end

  def profile
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to users_mypage_path
    else
      render :profile, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :prefecture_id, :age_id, :gender_id,
                                :job_id, :introduction, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yokutype</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/index.html.erb
<div>
  <h1 class="font-bold text-4xl">YokuType</h1>
  <% if user_signed_in? %>
  <%= link_to 'アカウント編集', edit_user_registration_path %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
  <%= link_to 'プロフィール編集', users_profile_path %>
  <%= link_to 'マイページ', users_mypage_path %>
  <% else %>
  <%= link_to 'サインアップ', new_user_registration_path %>
  <%= link_to 'ログイン', new_user_session_path %>
  <% end %>
</div>

app/views/users/mypage.html.erb
<div class="text-4xl">マイページ</div>
<%= @user.name %>
<%= @user.age_id.present? ? @user.age.name : '' %>
<%= @user.gender_id.present? ? @user.gender.type : '' %>
<%= @user.prefecture_id.present? ? @user.prefecture.name : '' %>
<%= @user.job_id.present? ? @user.job.name : '' %>
<%= @user.introduction %>
<%= image_tag(@user.thumbnail) %>

app/views/users/profile.html.erb
<div class="">プロフィール編集</div>
<%= form_with model: @user do |f| %>
  <%= f.label :name, "名前", class: "" %>
  <%= f.text_field :name, class: "" %>

  <%= f.label :prefecture, "都道府県", class: "" %>
  <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {include_blank: "---"} ) %>

  <%= f.label :age, "年齢", class: "" %>
  <%= f.collection_select(:age_id, Age.all, :id, :name, {include_blank: "---"} ) %>

  <%= f.label :gender, "性別", class: "" %>
  <%= f.collection_select(:gender_id, Gender.all, :id, :type, {include_blank: "---"} ) %>

  <%= f.label :job, "職業", class: "" %>
  <%= f.collection_select(:job_id, Job.all, :id, :name, {include_blank: "---"} ) %>

  <%= f.label :avatar, "アイコン画像", class: "" %>
  <%= f.file_field :avatar, class: "" %>

  <%= f.label :introduction, "自己紹介", class: "" %>
  <%= f.text_area :introduction, class: "", size: "20x10" %>

  <div class="">
  <%= f.submit "保存", class: "" %>
  <%= link_to "キャンセル", :back, class: "" %>
  </div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%= button_to "Sign in with Twitter", user_twitter2_omniauth_authorize_path, method: :post, data: { turbo: false } %>
<% end %>